version: '3.7'

services:
  postgres:
    image: 'postgres:12.16-alpine3.18'
    container_name: vpn_postgres
    env_file:
      - .env  # must define POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB
    volumes:
      - database-data:/var/lib/postgresql/data/  # persist data
    ports:
      - '8778:5432'  # required to access DB from host system

  web:
    build:
      context: .
    volumes:
      - ./:/usr/src/app/
      - static:/usr/src/app/static
      - gunicorn_socket:/gunicorn_socket
    ports:
      - '8000:8000'
      - '8001:8001'
    expose:
      - 8000
      - 8001
    env_file:
      - .env


volumes:
  static:
  gunicorn_socket:
  database-data:
